# Generated by Django 3.2.7 on 2021-09-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplaces',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
