# Generated by Django 3.2.7 on 2021-09-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
        ('review', '0001_initial'),
        ('resource', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('rating', models.ManyToManyField(to='rating.Rating')),
                ('resource', models.ManyToManyField(to='resource.Resource')),
                ('review', models.ManyToManyField(to='review.Review')),
            ],
        ),
        migrations.DeleteModel(
            name='TouristPlaces',
        ),
    ]
