# Generated by Django 3.2.7 on 2021-09-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('core', '0002_alter_touristplaces_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplaces',
            name='resources',
            field=models.ManyToManyField(to='resources.Resource'),
        ),
    ]
