# Generated by Django 3.2.7 on 2021-09-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210916_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
