# Generated by Django 3.2.7 on 2021-09-16 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_updated_at'),
        ('core', '0003_alter_touristplace_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
            preserve_default=False,
        ),
    ]
