# Generated by Django 3.2.7 on 2021-09-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_touristplace_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_place'),
        ),
    ]
